baseURL = "https://example.com"
title = "WebPages Archive" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
  posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "理工"
    url = "/science/"
    weight = 1

  [[menu.main]]
    name = "社科"
    url = "/social/"
    weight = 2

  [[menu.main]]
    name = "其它"
    url = "/others/"
    weight = 3

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 4

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 5

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 6

[params]
    since = 2020
    author = "Farenew"                          # Author's name
    avatar = ""           # Author's avatar
    # subtitle = "Just for Fun"                  # Subtitle
    home_mode = "post" # post or other
    enableGitalk = false # gitalk 评论系统

    google_verification = ""

    description = "Mogeko 的个人博客" # (Meta) 描述
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

[params.gitalk] # Github: https://github.com/gitalk/gitalk
    clientID = "" # Your client ID
    clientSecret = "" # Your client secret
    repo = "" # The repo to store comments
    owner = "" # Your GitHub ID
    admin= "" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
